{% set version = "1.0.0b1" %}

package:
  name: cftime
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cftime/cftime-{{ version }}.tar.gz
  sha256: a9b4b178f3ffc9b4133f337c143efca1f93ac24e132aba5471dc9419cc28b7be

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    # run_exports will take care of libnetcdf and hdf5
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - test
  requires:
    - pytest
  imports:
    - cftime
  commands:
    - py.test -vv test

about:
  home: https://github.com/Unidata/cftime
  license: MIT
  license_file: COPYING
  summary: 'Time-handling functionality from netcdf4-python'

  description: |
    Time-handling functionality from netcdf4-python
  doc_url: https://github.com/Unidata/cftime
  dev_url: https://github.com/Unidata/cftime

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
