{% set version = "1.6.4.post1" %}

package:
  name: cftime
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cftime/cftime-{{ version }}.tar.gz
  sha256: 50ac76cc9f10ab7bd46e44a71c51a6927051b499b4407df4f29ab13d741b942f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython >=0.29.20
    - numpy 2.0         # [py<313]
    - numpy {{ numpy }} # [py>=313]
    - setuptools >=41.2
    - wheel
  run:
    - python
    - numpy >=1.13.3,<3.0a0 # [py<312]
    - numpy >=1.26,<3.0a0   # [py>=312]

test:
  source_files:
    - test
  requires:
    - pytest
    - pip
  imports:
    - cftime
  commands:
    - pytest -vv test
    - pip check

about:
  home: https://github.com/Unidata/cftime
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Time-handling functionality from netcdf4-python
  description: |
    Time-handling functionality from netcdf4-python
  doc_url: https://github.com/Unidata/cftime
  dev_url: https://github.com/Unidata/cftime

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
