{% set version = "1.6.5" %}

package:
  name: cftime
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/cftime/cftime-{{ version }}.tar.gz
  sha256: 8225fed6b9b43fb87683ebab52130450fc1730011150d3092096a90e54d1e81e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<310]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython >=0.29.20
    - numpy >=2.0.0,<3
    - numpy {{ numpy }}  # [py>=313]
    - setuptools >=77.0.1
  run:
    - python
    - numpy >=1.13.3,<3.0a0  # [py<312]
    - numpy >=1.26,<3.0a0  # [py>=312]
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - test
  requires:
    - pytest
    - pip
  imports:
    - cftime
  commands:
    - pytest -vv test
    - pip check

about:
  home: https://github.com/Unidata/cftime
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Time-handling functionality from netcdf4-python
  description: |
    Time-handling functionality from netcdf4-python
  doc_url: https://github.com/Unidata/cftime
  dev_url: https://github.com/Unidata/cftime

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
