{% set version = "1.0.2.1" %}

package:
  name: cftime
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cftime/cftime-{{ version }}.tar.gz
  sha256: 2c81d4879a2c1753961d647e55e0125039ddeda195944c3d526f2cf087dfb7bb

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - test
  requires:
    - pytest
  imports:
    - cftime
  commands:
    - pytest -vv test

about:
  home: https://github.com/Unidata/cftime
  license: MIT
  license_file: COPYING
  summary: 'Time-handling functionality from netcdf4-python'

  description: |
    Time-handling functionality from netcdf4-python
  doc_url: https://github.com/Unidata/cftime
  dev_url: https://github.com/Unidata/cftime

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
