{% set name = "cftime" %}
{% set version = "1.6.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8225fed6b9b43fb87683ebab52130450fc1730011150d3092096a90e54d1e81e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<310]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - wheel
    - setuptools >=77.0.1
    - cython >=0.29.20
    - numpy {{ numpy }}
  run:
    - python
    - numpy >=1.21.2

test:
  source_files:
    - test
  imports:
    - cftime
  commands:
    - pip check
    - pytest -vv test
  requires:
    - pip
    - pytest

about:
  home: https://github.com/Unidata/cftime
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Time-handling functionality from netcdf4-python
  description: |
    Time-handling functionality from netcdf4-python
  doc_url: https://github.com/Unidata/cftime
  dev_url: https://github.com/Unidata/cftime

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
