{% set version = "1.6.2" %}

package:
  name: cftime
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cftime/cftime-{{ version }}.tar.gz
  sha256: 8614c00fb8a5046de304fdd86dbd224f99408185d7b245ac6628d0276596e6d2

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython 0.29
    - numpy {{numpy}}
    - setuptools
    - wheel
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - test
  requires:
    - pytest
    - pip
  imports:
    - cftime
  commands:
    # Re-enable this test in next release: https://github.com/Unidata/cftime/pull/294/files
    - pytest -vv test -k "not test_num2date_precision"
    - pip check

about:
  home: https://github.com/Unidata/cftime
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Time-handling functionality from netcdf4-python
  description: |
    Time-handling functionality from netcdf4-python
  doc_url: https://github.com/Unidata/cftime
  dev_url: https://github.com/Unidata/cftime

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
