# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangpython2.7
    - CONFIG=osx_c_compilerclangpython3.6
    - CONFIG=osx_c_compilerclangpython3.7
    - CONFIG=osx_c_compilertoolchain_cpython2.7
    - CONFIG=osx_c_compilertoolchain_cpython3.6
    - CONFIG=osx_c_compilertoolchain_cpython3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "P2FZTrP3GomDWDLcHgsWAWb0SOnWm/3ZSHomz+vvnceUgSICh4HI6bDoSouOIqZB2NTmolj9QIiXOokFXWqn+QwFbZIPHAMKDSHT2j1uYN21eQcRN/bgBh9CVVHz/W9D52RiOu8MT4O2L5OM5/oDeRHmydTQI7afEvfnxkDL9+IH9FMXly5iKkkbc8MrNgc3MDDpMjMklZ/GNDX1W+eLGSt32ERPLAfOPbt8bmtt7YHtK0S3qveMzY51LcEFmOckeAo9C8lrWCFBFCj7+foFP4PbpY5fSD0ZPCIJxqpL/3RObOY/57wmcCefbLZo3VGQL3Q1zDznkde9D7c5BlCNMOMeL0ATrzA7nPe5QhjFd3thokSfXnpJmrLsdAS8zjNQYjTBKhRruPvIymCUwitXMvN+COHAIP8GVewEgy9fJKzcgCFQGcxh/wbpAAnZFP+cfeeeqm4dztNluH1aDe5k1duJX+W1bwzaqncmpeQtggsVwnehKYQ9byitlGlV0dZgvdHQydd7C8KXM/gxkbduDhZeMpt4mbDRcS+/KcmQ5TaVuJQpB/Sgi6KnUk5Wr9oN2dO9x6mFyefu88q16yIbqNSgruKEw8PfwhaP+91RbRArzU+mC7SyFfSST1ivvEPNVDXTQHeI3W59S6iTfH30BRG6SVt2zdZd/iAIZ89aLtY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
