travis:
  secure:
    BINSTAR_TOKEN: iNjsNdPTV/+iwNjKODJae+2AopVP+PH8AErkjfh6r9lGKbz/6YB71zeWFA35FpRPC8/F/CM+HkONjTwIFYPPbvrlNhI/EXbO/7dzELcIP4NKNhy/zyN+vHvxK4/UkU9cYqyXydIiCUfoRg+FF6mjL9r3Er1zHh399shaFajoMBT9oLM1DYGv+vtCFI1uYcWgFBWO2dspz4CUHhvQXE+cqmqKXmxPImbwCAf74bRmHIFunMwtYsC4GuZbmnfFA6vU/TPSM6kqm9SFmHB+z7AtXb9flasuifGJcXlFA4um+n+8v/60uLy535OcOla4CdXJ7Mte0wV68vJxsm9AvaqDAIdDEAobF7NwBZ2fwv0xt/6scMpFJRJ1B0fu/a3KBl91QFQA9Rz/U9ym6PfQW/nL5pJpHvXFkysOGTSb35XK7hC34r1BIhrSi4RJIaPcx6pMRAZG5WDWaIc3fraJUlg37BcXVfsRtCS9USJ+7DJw2k9iS2GBndoxv/kT+GIAPFIlUaCETEFqUEBY+Ii9Sfi0uhwTEAxewLZKsTx1yfXiKiBFwsxioPJH2ikQcP156XsHTWEMDza/fWwq3+1PoyI5jPeyFwEjeNzF2k2kmswH4OSbNr7I+3FRPVo57MPaIBM9V/8MD/o1CmkyBw+8xgCao0kQzfmSzsLpkgXzqENwyxo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
